/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 31 16:23:17 GMT 2020
 */

package traz_aqui;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import traz_aqui.Coordenadas;
import traz_aqui.Loja;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Loja_ESTest extends Loja_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.9292089663166535, 0.9292089663166535);
      Loja loja0 = new Loja("x", "x", coordenadas0, 1028, "x", "x");
      boolean boolean0 = loja0.rangeLoja(coordenadas0, 4112.0);
      assertEquals(1028, loja0.getFila());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.0, 0.0);
      Loja loja0 = new Loja("H/!@Nf+%fJ!BY<7}~", "", coordenadas0, 895, "", "H/!@Nf+%fJ!BY<7}~");
      boolean boolean0 = loja0.rangeLoja(coordenadas0, (-479.560371277));
      assertEquals("", loja0.getEmail());
      assertFalse(boolean0);
      assertEquals("H/!@Nf+%fJ!BY<7}~", loja0.getCod());
      assertEquals("H/!@Nf+%fJ!BY<7}~", loja0.getPass());
      assertEquals("", loja0.getNome());
      assertEquals(895, loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(4053.63484403, 4053.63484403);
      Loja loja0 = new Loja("A{lkYqt5tUc(J#1*c", "A{lkYqt5tUc(J#1*c", coordenadas0, (-979), "QQhSu$\"(k>2", "traz_aqui.Loja");
      String string0 = loja0.getPass();
      assertEquals("QQhSu$\"(k>2", loja0.getEmail());
      assertEquals("A{lkYqt5tUc(J#1*c", loja0.getNome());
      assertEquals("traz_aqui.Loja", string0);
      assertEquals((-979), loja0.getFila());
      assertEquals("A{lkYqt5tUc(J#1*c", loja0.getCod());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2851.0, 0.0);
      Loja loja0 = new Loja("", "", coordenadas0, 0, "", "");
      loja0.getPass();
      assertEquals(0, loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(1941.687, 1941.687);
      Loja loja0 = new Loja("", (String) null, coordenadas0, 0, ") T{%\"y", ") T{%\"y");
      String string0 = loja0.getNome();
      assertEquals("", loja0.getCod());
      assertEquals(") T{%\"y", loja0.getPass());
      assertEquals(0, loja0.getFila());
      assertEquals(") T{%\"y", loja0.getEmail());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.0, 120.0);
      Loja loja0 = new Loja("Bi", "", coordenadas0, 0, "Bi", "");
      String string0 = loja0.getNome();
      assertEquals("", string0);
      assertEquals("Bi", loja0.getCod());
      assertEquals("Bi", loja0.getEmail());
      assertEquals(0, loja0.getFila());
      assertEquals("", loja0.getPass());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.0, 0.0);
      Loja loja0 = new Loja("", "\"1", coordenadas0, 0, "X: ", "lsf4`>~maOe_");
      int int0 = loja0.getFila();
      assertEquals(0, int0);
      assertEquals("\"1", loja0.getNome());
      assertEquals("lsf4`>~maOe_", loja0.getPass());
      assertEquals("X: ", loja0.getEmail());
      assertEquals("", loja0.getCod());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Loja loja0 = new Loja("", "", (Coordenadas) null, 805, (String) null, "");
      int int0 = loja0.getFila();
      assertEquals(805, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(1.0, 1.0);
      Loja loja0 = new Loja("jg`n>/jk(`", "jg`n>/jk(`", coordenadas0, 0, "jg`n>/jk(`", "jg`n>/jk(`");
      loja0.getEmail();
      assertEquals(0, loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Loja loja0 = new Loja("w+1|5F{e\"J", "w+1|5F{e\"J", (Coordenadas) null, (-1), "w+1|5F{e\"J", "traz_aqui.Coordenadas");
      assertEquals("w+1|5F{e\"J", loja0.getEmail());
      
      loja0.setEmail("");
      loja0.getEmail();
      assertEquals((-1), loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Loja loja0 = new Loja("X: ", "X: ", (Coordenadas) null, (-914), (String) null, (String) null);
      loja0.getCord();
      assertEquals((-914), loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.0, 0.0);
      Loja loja0 = new Loja("", "9r[", coordenadas0, (-121), "ll%EQ", "");
      loja0.getCord();
      assertEquals("9r[", loja0.getNome());
      assertEquals("", loja0.getPass());
      assertEquals("ll%EQ", loja0.getEmail());
      assertEquals((-121), loja0.getFila());
      assertEquals("", loja0.getCod());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.0, (-882.1682025090615));
      Loja loja0 = new Loja((String) null, (String) null, coordenadas0, 1537, "traz_aqui.Loja", "traz_aqui.Loja");
      loja0.getCord();
      assertEquals(1537, loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(4.0, 2117.659155359449);
      Loja loja0 = new Loja("d", "d", coordenadas0, 824, "", " Cp=qliV=G=]");
      loja0.getCord();
      assertEquals("d", loja0.getCod());
      assertEquals(" Cp=qliV=G=]", loja0.getPass());
      assertEquals(824, loja0.getFila());
      assertEquals("", loja0.getEmail());
      assertEquals("d", loja0.getNome());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.0, 0.0);
      Loja loja0 = new Loja((String) null, (String) null, coordenadas0, (-1), "", "");
      String string0 = loja0.getCod();
      assertNull(string0);
      assertEquals((-1), loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(129.16833019443, 129.16833019443);
      Loja loja0 = new Loja("", "", coordenadas0, 2194, "o_A>4H:T/7", "o_A>4H:T/7");
      String string0 = loja0.getCod();
      assertEquals("o_A>4H:T/7", loja0.getPass());
      assertEquals("", string0);
      assertEquals(2194, loja0.getFila());
      assertEquals("", loja0.getNome());
      assertEquals("o_A>4H:T/7", loja0.getEmail());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Loja loja0 = new Loja((String) null, (String) null, (Coordenadas) null, 0, (String) null, "|6<E7J(Ry?]?l");
      Loja loja1 = loja0.clone();
      assertEquals(0, loja1.getFila());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Loja loja0 = new Loja("D+ q", "D+ q", (Coordenadas) null, (-2444), "D+ q", "D+ q");
      Loja loja1 = loja0.clone();
      assertEquals((-2444), loja1.getFila());
      assertEquals((-2444), loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Loja loja0 = new Loja((String) null, (String) null, (Coordenadas) null, 0, "traz_aqui.Loja", (String) null);
      double double0 = loja0.calcTmp();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2193.3, 2193.3);
      Loja loja0 = new Loja("traz_aqui.Coordenadas", "Q86at85lcQnrZ ", coordenadas0, (-1998), "Q86at85lcQnrZ ", "Lne$p-=w/W1zjT-!n");
      double double0 = loja0.calcTmp();
      assertEquals("Q86at85lcQnrZ ", loja0.getNome());
      assertEquals((-7992.0), double0, 0.01);
      assertEquals("Q86at85lcQnrZ ", loja0.getEmail());
      assertEquals("traz_aqui.Coordenadas", loja0.getCod());
      assertEquals("Lne$p-=w/W1zjT-!n", loja0.getPass());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Loja loja0 = null;
      try {
        loja0 = new Loja((Loja) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.Loja", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas((-1422.459), (-1422.459));
      Loja loja0 = new Loja("t}*o.dziwa\u0001Uf5$@`", "t}*o.dziwa\u0001Uf5$@`", coordenadas0, 579, "t}*o.dziwa\u0001Uf5$@`", "t}*o.dziwa\u0001Uf5$@`");
      loja0.getNome();
      assertEquals(579, loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.0, (-1521.715));
      Loja loja0 = new Loja("><rR23,u<k<sBU9q", "><rR23,u<k<sBU9q", coordenadas0, 561, (String) null, (String) null);
      String string0 = loja0.getPass();
      assertNull(string0);
      assertEquals(561, loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.0, (-1521.715));
      Loja loja0 = new Loja("><rR23,u<k<sBU9q", "><rR23,u<k<sBU9q", coordenadas0, 561, (String) null, (String) null);
      String string0 = loja0.getEmail();
      assertNull(string0);
      assertEquals(561, loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas((-1422.459), (-1422.459));
      Loja loja0 = new Loja("t}*o.dziwa\u0001Uf5$@`", "t}*o.dziwa\u0001Uf5$@`", coordenadas0, 579, "t}*o.dziwa\u0001Uf5$@`", "t}*o.dziwa\u0001Uf5$@`");
      Loja loja1 = new Loja(loja0);
      assertEquals(579, loja0.getFila());
      assertEquals(579, loja1.getFila());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2193.3, 2193.3);
      Loja loja0 = new Loja("traz_aqui.Coordenadas", "Q86at85lcQnrZ ", coordenadas0, (-1998), "Q86at85lcQnrZ ", "Lne$p-=w/W1zjT-!n");
      String string0 = loja0.getCod();
      assertEquals("Lne$p-=w/W1zjT-!n", loja0.getPass());
      assertEquals((-1998), loja0.getFila());
      assertEquals("Q86at85lcQnrZ ", loja0.getNome());
      assertEquals("Q86at85lcQnrZ ", loja0.getEmail());
      assertEquals("traz_aqui.Coordenadas", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas((-1422.459), (-1422.459));
      Loja loja0 = new Loja("t}*o.dziwa\u0001Uf5$@`", "t}*o.dziwa\u0001Uf5$@`", coordenadas0, 579, "t}*o.dziwa\u0001Uf5$@`", "t}*o.dziwa\u0001Uf5$@`");
      loja0.getCord();
      assertEquals(579, loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2193.3, 2193.3);
      Loja loja0 = new Loja("traz_aqui.Coordenadas", "Q86at85lcQnrZ ", coordenadas0, (-1998), "Q86at85lcQnrZ ", "Lne$p-=w/W1zjT-!n");
      int int0 = loja0.getFila();
      assertEquals((-1998), int0);
      assertEquals("Q86at85lcQnrZ ", loja0.getNome());
      assertEquals("Q86at85lcQnrZ ", loja0.getEmail());
      assertEquals("traz_aqui.Coordenadas", loja0.getCod());
      assertEquals("Lne$p-=w/W1zjT-!n", loja0.getPass());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas((-15.53944601531505), (-15.53944601531505));
      Loja loja0 = new Loja((String) null, (String) null, coordenadas0, (-1), (String) null, (String) null);
      double double0 = loja0.calcTmp();
      //  // Unstable assertion: assertEquals(63.557438025008736, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.0, 0.0);
      Loja loja0 = new Loja("GH*Z", "GH*Z", coordenadas0, (-97), "GH*Z", "GH*Z");
      loja0.setPass("GH*Z");
      assertEquals((-97), loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.0, 0.0);
      Loja loja0 = new Loja("GH*Z", "GH*Z", coordenadas0, (-97), "GH*Z", "GH*Z");
      loja0.setNome("GH*Z");
      assertEquals((-97), loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2193.3, 2193.3);
      Loja loja0 = new Loja("traz_aqui.Coordenadas", "Q86at85lcQnrZ ", coordenadas0, (-1998), "Q86at85lcQnrZ ", "Lne$p-=w/W1zjT-!n");
      loja0.setFila((-1998));
      assertEquals("Lne$p-=w/W1zjT-!n", loja0.getPass());
      assertEquals((-1998), loja0.getFila());
      assertEquals("Q86at85lcQnrZ ", loja0.getEmail());
      assertEquals("traz_aqui.Coordenadas", loja0.getCod());
      assertEquals("Q86at85lcQnrZ ", loja0.getNome());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.9292089663166535, 0.9292089663166535);
      Loja loja0 = new Loja("x", "x", coordenadas0, 1028, "x", "x");
      loja0.setCod("x");
      assertEquals(1028, loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.9292089663166535, 0.9292089663166535);
      Loja loja0 = new Loja("x", "x", coordenadas0, 1028, "x", "x");
      Loja loja1 = loja0.clone();
      assertEquals(1028, loja1.getFila());
      assertEquals(1028, loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2193.3, 2193.3);
      Loja loja0 = new Loja("traz_aqui.Coordenadas", "Q86at85lcQnrZ ", coordenadas0, (-1998), "Q86at85lcQnrZ ", "Lne$p-=w/W1zjT-!n");
      // Undeclared exception!
      try { 
        loja0.rangeLoja((Coordenadas) null, 244.45070556);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.Coordenadas", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.0, 0.0);
      Loja loja0 = new Loja("GH*Z", "GH*Z", coordenadas0, (-97), "GH*Z", "GH*Z");
      loja0.setCord(coordenadas0);
      assertEquals((-97), loja0.getFila());
  }
}
