/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 31 16:24:43 GMT 2020
 */

package traz_aqui;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import traz_aqui.StringDistAux;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StringDistAux_ESTest extends StringDistAux_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      StringDistAux stringDistAux0 = new StringDistAux(0.0, "");
      stringDistAux0.setDist((-1007.102571497159));
      assertEquals((-1007.102571497159), stringDistAux0.dist, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      StringDistAux stringDistAux0 = new StringDistAux(2762.6067129276, "");
      double double0 = stringDistAux0.getDist();
      assertEquals(2762.6067129276, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      StringDistAux stringDistAux0 = new StringDistAux((-1.0), "1=~]j7A`62Sy)gSc<");
      double double0 = stringDistAux0.getDist();
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      StringDistAux stringDistAux0 = new StringDistAux(1.0, (String) null);
      stringDistAux0.getCod();
      assertEquals(1.0, stringDistAux0.dist, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      StringDistAux stringDistAux0 = new StringDistAux(0.0, "");
      String string0 = stringDistAux0.getCod();
      assertNotNull(string0);
      assertEquals(0.0, stringDistAux0.dist, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      StringDistAux stringDistAux0 = new StringDistAux(0.0, "");
      StringDistAux stringDistAux1 = stringDistAux0.clone();
      assertEquals(0.0, stringDistAux1.dist, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      StringDistAux stringDistAux0 = new StringDistAux((-529.81), "");
      StringDistAux stringDistAux1 = stringDistAux0.clone();
      assertEquals((-529.81), stringDistAux1.dist, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      StringDistAux stringDistAux0 = null;
      try {
        stringDistAux0 = new StringDistAux((StringDistAux) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.StringDistAux", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      StringDistAux stringDistAux0 = new StringDistAux(0.0, "WO85X!");
      double double0 = stringDistAux0.getDist();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      StringDistAux stringDistAux0 = new StringDistAux((-529.81), "");
      StringDistAux stringDistAux1 = new StringDistAux(stringDistAux0);
      assertEquals((-529.81), stringDistAux1.dist, 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      StringDistAux stringDistAux0 = new StringDistAux((-528.8508685267), "X_/VRco#Xx3_cDq|$e<");
      String string0 = stringDistAux0.getCod();
      assertEquals((-528.8508685267), stringDistAux0.dist, 0.01);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      StringDistAux stringDistAux0 = new StringDistAux(515.728490275199, "traz_aqui.StringDistAux");
      stringDistAux0.setCod("traz_aqui.StringDistAux");
      assertEquals(515.728490275199, stringDistAux0.dist, 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      StringDistAux stringDistAux0 = new StringDistAux(515.728490275199, "traz_aqui.StringDistAux");
      StringDistAux stringDistAux1 = stringDistAux0.clone();
      assertEquals(515.728490275199, stringDistAux1.dist, 0.01);
  }
}
