/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 31 16:28:39 GMT 2020
 */

package traz_aqui;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import traz_aqui.TopUsers;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TopUsers_ESTest extends TopUsers_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TopUsers topUsers0 = new TopUsers("");
      topUsers0.addKm(1.0);
      double double0 = topUsers0.getQnt();
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TopUsers topUsers0 = new TopUsers("");
      topUsers0.addKm((-89.29268));
      double double0 = topUsers0.getQnt();
      assertEquals((-89.29268), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TopUsers topUsers0 = new TopUsers((String) null);
      topUsers0.getCod();
      assertEquals(0.0, topUsers0.getQnt(), 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TopUsers topUsers0 = new TopUsers("Q,*\"+l=4Xg2)r?!");
      topUsers0.getCod();
      assertEquals(0.0, topUsers0.getQnt(), 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TopUsers topUsers0 = new TopUsers("jrl");
      topUsers0.addQnt();
      assertEquals(1.0, topUsers0.getQnt(), 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TopUsers topUsers0 = new TopUsers("");
      double double0 = topUsers0.getQnt();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TopUsers topUsers0 = new TopUsers("jrl");
      String string0 = topUsers0.toString();
      assertEquals("Quantidade: 0.0-jrl", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      TopUsers topUsers0 = new TopUsers("");
      topUsers0.setCod("");
      assertEquals(0.0, topUsers0.getQnt(), 0.01);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      TopUsers topUsers0 = new TopUsers("jrl");
      topUsers0.setQnt((-3189));
      assertEquals((-3189.0), topUsers0.getQnt(), 0.01);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      TopUsers topUsers0 = new TopUsers("");
      topUsers0.getCod();
      assertEquals(0.0, topUsers0.getQnt(), 0.01);
  }
}
