package traz_aqui;/*
 * This file was automatically generated by EvoSuite
 * Sun Dec 20 00:26:04 GMT 2020
 */

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CatTransportadoras_ESTest extends CatTransportadoras_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas((-1808.5), 0.0);
      catTransportadoras0.signupT("", (String) null, coordenadas0, 0.0, 1.0, (-697.0), (-697.0), true, 0.0, "I13", "traz_aqui.StringDistAux", (-1808.5), 0);
      Coordenadas coordenadas1 = new Coordenadas(coordenadas0);
      coordenadas0.setX(0.0);
      catTransportadoras0.addKmps("", coordenadas1, coordenadas0);
      assertEquals(0.0, coordenadas0.getX(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      catTransportadoras0.signupT("", "ZMhu0=>", (Coordenadas) null, (-1794.0761065451), (-1794.0761065451), 0.0, 0.0, false, (-1.0), "", "ZMhu0=>", 2.0, 879);
      Coordenadas coordenadas0 = new Coordenadas((-1808.5), 0.0);
      Coordenadas coordenadas1 = new Coordenadas(coordenadas0);
      // Undeclared exception!
      try { 
        catTransportadoras0.addKmps("", coordenadas1, coordenadas0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.CatTransportadoras", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas(3053.374309322098, 3053.374309322098);
      Coordenadas coordenadas1 = coordenadas0.clone();
      // Undeclared exception!
      try { 
        catTransportadoras0.calcCost(coordenadas0, coordenadas1, 1370.61935, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.CatTransportadoras", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      catTransportadoras0.signupT("", "[yD@SIZI!l", (Coordenadas) null, (-2019.48225), 995.3, 995.3, 0.0, false, (-204.984871), "", "sp]m*+6M/.I^", 142.506031045539, (-1));
      String string0 = catTransportadoras0.loginT("", "");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas(3053.374309322098, 3053.374309322098);
      Coordenadas coordenadas1 = new Coordenadas(coordenadas0);
      List<StringDistAux> list0 = catTransportadoras0.melhorTransporteT(coordenadas1, coordenadas0, false);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas(1237.31, 1237.31);
      catTransportadoras0.signupT(")Fyxli=L|tv", ")Fyxli=L|tv", coordenadas0, 1237.31, 1237.31, 0.0, 0.0, true, 318.706, ")Fyxli=L|tv", ")Fyxli=L|tv", 0.0, 1);
      catTransportadoras0.dimCap(")Fyxli=L|tv");
      assertEquals(1, catTransportadoras0.size());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      catTransportadoras0.signupT("", "[yD@SIZI!l", (Coordenadas) null, (-2019.48225), 995.3, 995.3, 0.0, false, (-204.984871), "", "sp]m*+6M/.I^", 142.506031045539, (-1));
      catTransportadoras0.aumCap("");
      assertEquals(1, catTransportadoras0.size());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      catTransportadoras0.signupT("", "", (Coordenadas) null, (-2019.48225), (-2019.48225), (-2019.48225), (-2019.48225), false, (-204.984871), "", "", 142.506031045539, (-1));
      catTransportadoras0.adicionaCla("", (-1));
      assertEquals(1, catTransportadoras0.size());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas((-930.4674093), (-2377.32045249074));
      catTransportadoras0.signupT("w13+Va4z,jjC<v", "newpg79G>u", coordenadas0, 0.0, (-228.8442368), (-930.4674093), 0.0, true, (-2377.32045249074), "newpg79G>u", "w13+Va4z,jjC<v", 1256.3204, (-2454));
      boolean boolean0 = catTransportadoras0.verMail("newpg79G>u");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas(3053.374309322098, 3053.374309322098);
      catTransportadoras0.signupT((String) null, (String) null, coordenadas0, 3053.374309322098, 1372.86946, 0.0, 3887.261544489193, true, 0.0, "X: ", (String) null, 3053.374309322098, 10);
      int int0 = catTransportadoras0.size();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas(3053.374309322098, 3053.374309322098);
      catTransportadoras0.signupT((String) null, (String) null, coordenadas0, 3053.374309322098, 1372.86946, 0.0, 3887.261544489193, true, 0.0, "X: ", (String) null, 3053.374309322098, 10);
      List<StringDistAux> list0 = catTransportadoras0.melhorTransporteT(coordenadas0, coordenadas0, false);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      catTransportadoras0.signupT("", "", (Coordenadas) null, (-2019.48225), (-2019.48225), (-2019.48225), (-2019.48225), false, (-204.984871), "", "", 142.506031045539, (-1));
      String string0 = catTransportadoras0.loginT("", "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas((-333.6), (-333.6));
      catTransportadoras0.signupT("", "", coordenadas0, (-2094.0319), 0.0, (-2094.0319), 619.0800616572, true, 0.0, "*6|?%^rEqR]8nH]DL", "", 0.0, (-2383));
      double double0 = catTransportadoras0.getKmp("");
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas((-3020.0), 210.624098509);
      Transportadoras transportadoras0 = new Transportadoras("s/rE3v=SNa:yu", "- Y:", coordenadas0, (-3020.0), 210.624098509, 703.4035087011248, 1690.7786290331, true, 210.624098509, "vh<(", "s/rE3v=SNa:yu", 1905.683, 1902);
      catTransportadoras0.adicionaTrans(transportadoras0);
      double double0 = catTransportadoras0.getKmp("s/rE3v=SNa:yu");
      assertEquals(1905.683, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas(70.82070566898624, 2302.9709477829433);
      catTransportadoras0.signupT("newpg779z>T", "newpg779z>T", coordenadas0, 70.82070566898624, 70.82070566898624, 2371.0, 2371.0, true, 70.82070566898624, "traz_aqui.CatTransportadoras", "newpg779z>T", (-1753.4612), (-1431655764));
      double double0 = catTransportadoras0.getKmp("newpg779z>T");
      assertEquals((-1753.4612), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas(0.0, (-2149.0));
      catTransportadoras0.signupT("w<Q/+G;{9]G,,{>qJ", "dRM2B885rraAq", coordenadas0, 0.0, 0.0, 0.0, 2489.56956, true, 2489.56956, "traz_aqui.CatTransportadoras", "", 2043.4, (-3784));
      Coordenadas coordenadas1 = catTransportadoras0.getCord("w<Q/+G;{9]G,,{>qJ");
      assertEquals(0.0, coordenadas1.getX(), 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas(70.82070566898624, 2302.9709477829433);
      catTransportadoras0.signupT("newpg779z>T", "newpg779z>T", coordenadas0, 70.82070566898624, 70.82070566898624, 2371.0, 2371.0, true, 70.82070566898624, "traz_aqui.CatTransportadoras", "newpg779z>T", (-1753.4612), (-1431655764));
      Coordenadas coordenadas1 = catTransportadoras0.getCord("newpg779z>T");
      assertNotSame(coordenadas1, coordenadas0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas((-4899.012983273), 0.0);
      catTransportadoras0.signupT("J7VyHoJc3CONub", (String) null, coordenadas0, 3103.358345, 3103.358345, 3103.358345, 638.84762181788, false, (-2139.799169844374), "I;2Rp\u0007iBo%08kD", (String) null, (-2139.799169844374), 0);
      Coordenadas coordenadas1 = catTransportadoras0.getCord("J7VyHoJc3CONub");
      assertNotSame(coordenadas1, coordenadas0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Transportadoras transportadoras0 = new Transportadoras((String) null, "t96", (Coordenadas) null, 2407.0, 2407.0, 2407.0, 2407.0, true, 2407.0, "t97", (String) null, 2407.0, 1364);
      catTransportadoras0.adicionaTrans(transportadoras0);
      double double0 = catTransportadoras0.getClas((String) null);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas(879, 0.0);
      catTransportadoras0.signupT("", (String) null, coordenadas0, 0.0, 1.0, 879, 879, true, 0.0, "I13", "traz_aqui.StringDistAux", 879, 879);
      double double0 = catTransportadoras0.getClas("");
      assertEquals(879.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      catTransportadoras0.signupT("", "", (Coordenadas) null, (-2019.48225), (-2019.48225), (-2019.48225), (-2019.48225), false, (-204.984871), "", "", 142.506031045539, (-1));
      double double0 = catTransportadoras0.getClas("");
      assertEquals((-2019.48225), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas((-3020.0), 210.624098509);
      Transportadoras transportadoras0 = new Transportadoras("s/rE3v=SNa:yu", "- Y:", coordenadas0, (-3020.0), 210.624098509, 703.4035087011248, 1690.7786290331, true, 210.624098509, "vh<(", "s/rE3v=SNa:yu", 1905.683, 1902);
      catTransportadoras0.adicionaTrans(transportadoras0);
      int int0 = catTransportadoras0.getCap("s/rE3v=SNa:yu");
      assertEquals(1902, int0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas(70.82070566898624, 2302.9709477829433);
      catTransportadoras0.signupT("newpg779z>T", "newpg779z>T", coordenadas0, 70.82070566898624, 70.82070566898624, 2371.0, 2371.0, true, 70.82070566898624, "traz_aqui.CatTransportadoras", "newpg779z>T", (-1753.4612), (-1431655764));
      int int0 = catTransportadoras0.getCap("newpg779z>T");
      assertEquals((-1431655764), int0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas((-1.0), (-1.0));
      catTransportadoras0.signupT("=U", "traz_aqui.CatTransportadoras", coordenadas0, (-1.0), 0.0, 2708.695612, 5318.370992620667, false, 0.5, "j", "", 0.5, (-155));
      Double double0 = new Double(0.0);
      double double1 = catTransportadoras0.calcTmp(coordenadas0, coordenadas0, double0, "=U");
      assertEquals(0.0, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas((-930.4674093), (-2377.32045249074));
      catTransportadoras0.signupT("wu+Va4zm,jjCv", "newpg79G>u", coordenadas0, 0.0, (-228.8442368), (-930.4674093), 0.0, true, (-2377.32045249074), "newpg79G>u", "newpg79G<u", 1256.3204, (-2454));
      Double double0 = Double.valueOf(28.005667572668997);
      double double1 = catTransportadoras0.calcTmp(coordenadas0, coordenadas0, double0, "wu+Va4zm,jjCv");
      assertEquals(28.005667572668997, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas((-930.4674093), (-1595.573));
      catTransportadoras0.signupT("wu+Va4zm,jjCv", "newpg79G>u", coordenadas0, 0.0, (-232.37813899989746), (-930.4674093), 0.0, true, (-1595.573), "newpg79G>u", "newpg79G<u", 1256.3204, (-2454));
      Double double0 = new Double((-232.37813899989746));
      double double1 = catTransportadoras0.calcTmp(coordenadas0, coordenadas0, double0, "wu+Va4zm,jjCv");
      assertEquals((-232.37813899989746), double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas((-2377.32045249074), (-2377.32045249074));
      catTransportadoras0.signupT("wu+Va4zm,jjCv", "newpg79G>u", coordenadas0, (-2377.32045249074), (-2377.32045249074), (-2377.32045249074), (-2377.32045249074), false, (-2377.32045249074), "newpg79G>u", "newpg79G<u", (-2377.32045249074), 4918);
      double double0 = catTransportadoras0.calcCost(coordenadas0, coordenadas0, 0.0, "wu+Va4zm,jjCv");
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas(3053.374309322098, 3053.374309322098);
      catTransportadoras0.signupT((String) null, (String) null, coordenadas0, 3053.374309322098, 1372.86946, 0.0, 3887.261544489193, true, 0.0, "X: ", (String) null, 3053.374309322098, 10);
      double double0 = catTransportadoras0.calcCost(coordenadas0, coordenadas0, 1370.61935, (String) null);
      assertEquals(685.309675, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas((-4899.012983273), 0.0);
      catTransportadoras0.signupT("J7VyHoJc3CONub", (String) null, coordenadas0, 3103.358345, 3103.358345, 3103.358345, 638.84762181788, false, (-2139.799169844374), "I;2Rp\u0007iBo%08kD", (String) null, (-2139.799169844374), 0);
      double double0 = catTransportadoras0.calcCost(coordenadas0, coordenadas0, (-3654.3723962642), "J7VyHoJc3CONub");
      assertEquals((-1827.1861981321), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas((-1811.2408), (-1811.2408));
      catTransportadoras0.signupT("t", (String) null, coordenadas0, (-58.83), 5392.0245809283, (-1811.2408), 2955.23410097133, false, (-58.83), (String) null, "t", 0.0, (-2693));
      // Undeclared exception!
      try { 
        catTransportadoras0.verMail((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Transportadoras transportadoras0 = new Transportadoras((String) null, "t96", (Coordenadas) null, 2407.0, 2407.0, 2407.0, 2407.0, true, 2407.0, "t97", (String) null, 2407.0, 1364);
      catTransportadoras0.adicionaTrans(transportadoras0);
      // Undeclared exception!
      try { 
        catTransportadoras0.melhorTransporteT((Coordenadas) null, (Coordenadas) null, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.Transportadoras", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas((-3906.7504818036014), (-4930.17612));
      catTransportadoras0.signupT((String) null, "#", coordenadas0, (-3906.7504818036014), 0.0, 0.0, (-4930.17612), false, (-4930.17612), (String) null, "@'[7<)OK1\"Y", (-3906.7504818036014), 0);
      // Undeclared exception!
      try { 
        catTransportadoras0.loginT("0-[.Ie8lJ'_&*{&}Rk", "#");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      // Undeclared exception!
      try { 
        catTransportadoras0.adicionaTrans((Transportadoras) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.CatTransportadoras", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Transportadoras transportadoras0 = new Transportadoras((String) null, "t96", (Coordenadas) null, 2407.0, 2407.0, 2407.0, 2407.0, true, 2407.0, "t97", (String) null, 2407.0, 1364);
      catTransportadoras0.adicionaTrans(transportadoras0);
      String string0 = catTransportadoras0.codUnicoT();
      //  // Unstable assertion: assertEquals("t43", string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      String string0 = catTransportadoras0.codUnicoT();
      //  // Unstable assertion: assertNotNull(string0);
      //  // Unstable assertion: assertEquals("t21", string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      catTransportadoras0.signupT("traz_aqui.Coordenadas", "traz_aqui.Coordenadas", (Coordenadas) null, (-2020.668), (-2020.668), (-2020.668), (-2020.668), true, (-2020.668), "traz_aqui.Coordenadas", "traz_aqui.Coordenadas", (-2020.668), 7);
      String string0 = catTransportadoras0.loginT("traz_aqui.Coordenadas", "traz_aqui.Coordenadas");
      assertEquals("traz_aqui.Coordenadas", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Transportadoras transportadoras0 = new Transportadoras((String) null, "t96", (Coordenadas) null, 2407.0, 2407.0, 2407.0, 2407.0, true, 2407.0, "t97", (String) null, 2407.0, 1364);
      catTransportadoras0.adicionaTrans(transportadoras0);
      String string0 = catTransportadoras0.loginT("t96", "t97");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      // Undeclared exception!
      try { 
        catTransportadoras0.getCap("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.CatTransportadoras", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      // Undeclared exception!
      try { 
        catTransportadoras0.dimCap("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.CatTransportadoras", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      // Undeclared exception!
      try { 
        catTransportadoras0.getClas("t85");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.CatTransportadoras", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      // Undeclared exception!
      try { 
        catTransportadoras0.adicionaCla(".\"3;", 0.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.CatTransportadoras", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      int int0 = catTransportadoras0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Coordenadas coordenadas0 = new Coordenadas(679, 679);
      Double double0 = new Double(679);
      // Undeclared exception!
      try { 
        catTransportadoras0.calcTmp(coordenadas0, (Coordenadas) null, double0, "Uwg");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.CatTransportadoras", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      // Undeclared exception!
      try { 
        catTransportadoras0.getKmp("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.CatTransportadoras", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      Transportadoras transportadoras0 = new Transportadoras((String) null, "t96", (Coordenadas) null, 2407.0, 2407.0, 2407.0, 1010.31173305, true, 1010.31173305, "t97", (String) null, 2407.0, 1367);
      catTransportadoras0.adicionaTrans(transportadoras0);
      catTransportadoras0.setCoords((String) null, (Coordenadas) null);
      assertEquals(1, catTransportadoras0.size());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      // Undeclared exception!
      try { 
        catTransportadoras0.getCord("newpg79G<u");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.CatTransportadoras", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      // Undeclared exception!
      try { 
        catTransportadoras0.aumCap("b_Sw");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.CatTransportadoras", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      // Undeclared exception!
      try { 
        catTransportadoras0.setCoords((String) null, (Coordenadas) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.CatTransportadoras", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      CatTransportadoras catTransportadoras0 = new CatTransportadoras();
      boolean boolean0 = catTransportadoras0.verMail((String) null);
      assertFalse(boolean0);
  }
}
