package traz_aqui;/*
 * This file was automatically generated by EvoSuite
 * Sun Dec 20 00:33:51 GMT 2020
 */

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Loja_ESTest extends Loja_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2.0, (-962.02755361115));
      Loja loja0 = new Loja("V$v/@A", (String) null, coordenadas0, 0, "", "");
      boolean boolean0 = loja0.rangeLoja(coordenadas0, 2.0);
      assertEquals("", loja0.getEmail());
      assertEquals("V$v/@A", loja0.getCod());
      assertTrue(boolean0);
      assertEquals(0, loja0.getFila());
      assertEquals("", loja0.getPass());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas((-2673.181835644262), (-2673.181835644262));
      Loja loja0 = new Loja("o\":y4a}6j", "o\":y4a}6j", coordenadas0, (-471), "o\":y4a}6j", "o\":y4a}6j");
      boolean boolean0 = loja0.rangeLoja(coordenadas0, (-471));
      assertFalse(boolean0);
      assertEquals((-471), loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.0, (-1521.715));
      Loja loja0 = new Loja("><rR23,u<k<sBU9q", "><rR23,u<k<sBU9q", coordenadas0, 561, (String) null, (String) null);
      String string0 = loja0.getPass();
      assertEquals(561, loja0.getFila());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Loja loja0 = new Loja((String) null, (String) null, (Coordenadas) null, 1424, "fAt7", "");
      String string0 = loja0.getPass();
      assertNotNull(string0);
      assertEquals("fAt7", loja0.getEmail());
      assertEquals(1424, loja0.getFila());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2387.0, 1.0);
      Loja loja0 = new Loja((String) null, (String) null, coordenadas0, 315, (String) null, "hW^E8gf'i1X~<(?k");
      String string0 = loja0.getNome();
      assertEquals(315, loja0.getFila());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(1854.629235235, 1854.629235235);
      Loja loja0 = new Loja("85XD>]lZs|WrDfwx~", "SXH`(d", coordenadas0, (-1), "85XD>]lZs|WrDfwx~", "85XD>]lZs|WrDfwx~");
      String string0 = loja0.getNome();
      assertEquals("85XD>]lZs|WrDfwx~", loja0.getCod());
      assertEquals("85XD>]lZs|WrDfwx~", loja0.getPass());
      assertEquals("SXH`(d", string0);
      assertEquals((-1), loja0.getFila());
      assertEquals("85XD>]lZs|WrDfwx~", loja0.getEmail());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas((-1496.5800386), 120.0);
      Loja loja0 = new Loja("sSnNX=mO)", "b", coordenadas0, 0, ";1,Y|.?:;}_E'1E1", (String) null);
      int int0 = loja0.getFila();
      assertEquals(0, int0);
      assertEquals("sSnNX=mO)", loja0.getCod());
      assertEquals("b", loja0.getNome());
      assertEquals(";1,Y|.?:;}_E'1E1", loja0.getEmail());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Loja loja0 = new Loja("", "", (Coordenadas) null, 805, (String) null, "");
      int int0 = loja0.getFila();
      assertEquals(805, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.0, (-1521.715));
      Loja loja0 = new Loja("><rR23,u<k<sBU9q", "><rR23,u<k<sBU9q", coordenadas0, 561, (String) null, (String) null);
      String string0 = loja0.getEmail();
      assertEquals(561, loja0.getFila());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Loja loja0 = new Loja("w+1|5F{e\"J", "w+1|5F{e\"J", (Coordenadas) null, (-1), "w+1|5F{e\"J", "traz_aqui.Coordenadas");
      assertEquals("w+1|5F{e\"J", loja0.getEmail());
      
      loja0.setEmail("");
      loja0.getEmail();
      assertEquals("w+1|5F{e\"J", loja0.getCod());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Loja loja0 = new Loja("X: ", "X: ", (Coordenadas) null, (-914), (String) null, (String) null);
      loja0.getCord();
      assertEquals((-914), loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.0, (-1.0));
      Loja loja0 = new Loja("", "", coordenadas0, (-1051), "", "");
      loja0.getCord();
      assertEquals((-1051), loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2321.8739329, 0.0);
      Loja loja0 = new Loja("", "", coordenadas0, 0, "", "- Y:");
      loja0.getCord();
      assertEquals("- Y:", loja0.getPass());
      assertEquals(0, loja0.getFila());
      assertEquals("", loja0.getNome());
      assertEquals("", loja0.getCod());
      assertEquals("", loja0.getEmail());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2387.0, 1.0);
      Loja loja0 = new Loja((String) null, (String) null, coordenadas0, 315, (String) null, "hW^E8gf'i1X~<(?k");
      String string0 = loja0.getCod();
      assertEquals(315, loja0.getFila());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(3336.414671882318, (-1858.26));
      Loja loja0 = new Loja("", "", coordenadas0, 1987, "", "");
      loja0.getCod();
      assertEquals(1987, loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas((-1496.5800386), 120.0);
      Loja loja0 = new Loja("sSnNX=mO)", "b", coordenadas0, 0, ";1,Y|.?:;}_E'1E1", (String) null);
      Loja loja1 = loja0.clone();
      assertEquals(0, loja1.getFila());
      assertEquals(";1,Y|.?:;}_E'1E1", loja1.getEmail());
      assertEquals("b", loja1.getNome());
      assertEquals("sSnNX=mO)", loja1.getCod());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2387.0, 1.0);
      Loja loja0 = new Loja((String) null, (String) null, coordenadas0, 315, (String) null, "hW^E8gf'i1X~<(?k");
      Loja loja1 = loja0.clone();
      assertEquals(315, loja0.getFila());
      assertEquals(315, loja1.getFila());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas((-1496.5800386), 120.0);
      Loja loja0 = new Loja("sSnNX=mO)", "b", coordenadas0, 0, ";1,Y|.?:;}_E'1E1", (String) null);
      double double0 = loja0.calcTmp();
      assertEquals(";1,Y|.?:;}_E'1E1", loja0.getEmail());
      assertEquals(0.0, double0, 0.01);
      assertEquals("sSnNX=mO)", loja0.getCod());
      assertEquals("b", loja0.getNome());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Loja loja0 = null;
      try {
        loja0 = new Loja((Loja) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.Loja", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(0.0, 120.0);
      Loja loja0 = new Loja("Bi", "", coordenadas0, 0, "Bi", "");
      String string0 = loja0.getNome();
      assertEquals(0, loja0.getFila());
      assertEquals("Bi", loja0.getEmail());
      assertEquals("Bi", loja0.getCod());
      assertEquals("", string0);
      assertEquals("", loja0.getPass());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas((-291.7), (-3322.56506306));
      Loja loja0 = new Loja("yh/}$z.pdD[", "", coordenadas0, 1925, "yh/}$z.pdD[", "QzIg3TaEV {");
      String string0 = loja0.getPass();
      assertEquals("QzIg3TaEV {", string0);
      assertEquals(1925, loja0.getFila());
      assertEquals("yh/}$z.pdD[", loja0.getCod());
      assertEquals("", loja0.getNome());
      assertEquals("yh/}$z.pdD[", loja0.getEmail());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas((-291.7), (-3322.56506306));
      Loja loja0 = new Loja("yh/}$z.pdD[", "", coordenadas0, 1925, "yh/}$z.pdD[", "QzIg3TaEV {");
      String string0 = loja0.getEmail();
      assertEquals(1925, loja0.getFila());
      assertEquals("yh/}$z.pdD[", string0);
      assertEquals("", loja0.getNome());
      assertEquals("yh/}$z.pdD[", loja0.getCod());
      assertEquals("QzIg3TaEV {", loja0.getPass());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas((-291.7), (-3322.56506306));
      Loja loja0 = new Loja("yh/}$z.pdD[", "", coordenadas0, 1925, "yh/}$z.pdD[", "QzIg3TaEV {");
      Loja loja1 = new Loja(loja0);
      assertEquals("QzIg3TaEV {", loja1.getPass());
      assertEquals(1925, loja0.getFila());
      assertEquals("", loja1.getNome());
      assertEquals("yh/}$z.pdD[", loja1.getEmail());
      assertEquals("yh/}$z.pdD[", loja1.getCod());
      assertEquals(1925, loja1.getFila());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2193.3, 2193.3);
      Loja loja0 = new Loja("traz_aqui.Coordenadas", "Q86at85lcQnrZ ", coordenadas0, (-1998), "Q86at85lcQnrZ ", "Lne$p-=w/W1zjT-!n");
      String string0 = loja0.getCod();
      assertEquals("Q86at85lcQnrZ ", loja0.getEmail());
      assertEquals("traz_aqui.Coordenadas", string0);
      assertEquals("Lne$p-=w/W1zjT-!n", loja0.getPass());
      assertEquals("Q86at85lcQnrZ ", loja0.getNome());
      assertEquals((-1998), loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas((-1496.5800386), 120.0);
      Loja loja0 = new Loja("sSnNX=mO)", "b", coordenadas0, 0, ";1,Y|.?:;}_E'1E1", (String) null);
      loja0.getCord();
      assertEquals(";1,Y|.?:;}_E'1E1", loja0.getEmail());
      assertEquals(0, loja0.getFila());
      assertEquals("b", loja0.getNome());
      assertEquals("sSnNX=mO)", loja0.getCod());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2193.3, 2193.3);
      Loja loja0 = new Loja("traz_aqui.Coordenadas", "Q86at85lcQnrZ ", coordenadas0, (-1998), "Q86at85lcQnrZ ", "Lne$p-=w/W1zjT-!n");
      int int0 = loja0.getFila();
      assertEquals("Lne$p-=w/W1zjT-!n", loja0.getPass());
      assertEquals("Q86at85lcQnrZ ", loja0.getEmail());
      assertEquals("traz_aqui.Coordenadas", loja0.getCod());
      assertEquals("Q86at85lcQnrZ ", loja0.getNome());
      assertEquals((-1998), int0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Loja loja0 = new Loja("", "", (Coordenadas) null, (-1), "", "");
      double double0 = loja0.calcTmp();
      //  // Unstable assertion: assertEquals(92.88935179126727, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas((-2673.181835644262), (-2673.181835644262));
      Loja loja0 = new Loja("o\":y4a}6j", "o\":y4a}6j", coordenadas0, (-471), "o\":y4a}6j", "o\":y4a}6j");
      double double0 = loja0.calcTmp();
      assertEquals((-1884.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2193.3, 2193.3);
      Loja loja0 = new Loja("traz_aqui.Coordenadas", "Q86at85lcQnrZ ", coordenadas0, (-1998), "Q86at85lcQnrZ ", "Lne$p-=w/W1zjT-!n");
      assertEquals("Lne$p-=w/W1zjT-!n", loja0.getPass());
      
      loja0.setPass("- Y:");
      assertEquals((-1998), loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas((-2673.181835644262), (-2673.181835644262));
      Loja loja0 = new Loja("o\":y4a}6j", "o\":y4a}6j", coordenadas0, (-471), "o\":y4a}6j", "o\":y4a}6j");
      loja0.setNome("o\":y4a}6j");
      assertEquals((-471), loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2193.3, 2193.3);
      Loja loja0 = new Loja("traz_aqui.Coordenadas", "Q86at85lcQnrZ ", coordenadas0, (-1998), "Q86at85lcQnrZ ", "Lne$p-=w/W1zjT-!n");
      loja0.setFila((-1998));
      assertEquals("Lne$p-=w/W1zjT-!n", loja0.getPass());
      assertEquals((-1998), loja0.getFila());
      assertEquals("Q86at85lcQnrZ ", loja0.getEmail());
      assertEquals("traz_aqui.Coordenadas", loja0.getCod());
      assertEquals("Q86at85lcQnrZ ", loja0.getNome());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Loja loja0 = new Loja("", "", (Coordenadas) null, (-1), "", "");
      loja0.setCod("");
      assertEquals((-1), loja0.getFila());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas((-2673.181835644262), (-2673.181835644262));
      Loja loja0 = new Loja("o\":y4a}6j", "o\":y4a}6j", coordenadas0, (-471), "o\":y4a}6j", "o\":y4a}6j");
      Loja loja1 = loja0.clone();
      assertEquals((-471), loja0.getFila());
      assertEquals((-471), loja1.getFila());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2193.3, 2193.3);
      Loja loja0 = new Loja("traz_aqui.Coordenadas", "Q86at85lcQnrZ ", coordenadas0, (-1998), "Q86at85lcQnrZ ", "Lne$p-=w/W1zjT-!n");
      // Undeclared exception!
      try { 
        loja0.rangeLoja((Coordenadas) null, 244.45070556);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("traz_aqui.Coordenadas", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Coordenadas coordenadas0 = new Coordenadas(2193.3, 2193.3);
      Loja loja0 = new Loja("traz_aqui.Coordenadas", "Q86at85lcQnrZ ", coordenadas0, (-1998), "Q86at85lcQnrZ ", "Lne$p-=w/W1zjT-!n");
      loja0.setCord(coordenadas0);
      assertEquals((-1998), loja0.getFila());
      assertEquals("Lne$p-=w/W1zjT-!n", loja0.getPass());
      assertEquals("traz_aqui.Coordenadas", loja0.getCod());
      assertEquals("Q86at85lcQnrZ ", loja0.getNome());
      assertEquals("Q86at85lcQnrZ ", loja0.getEmail());
  }
}
