module Names where


firstNames :: [String]
firstNames =
  ["James","Mary","John","Patricia","Robert","Jennifer","Michael","Linda","William","Elizabeth","David","Barbara","Richard","Susan","Joseph","Jessica","Thomas","Sarah","Charles","Karen","Christopher","Nancy","Daniel","Lisa","Matthew","Margaret","Anthony","Betty","Donald","Sandra","Mark","Ashley","Paul","Dorothy","Steven","Kimberly","Andrew","Emily","Kenneth","Donna","Joshua","Michelle","Kevin","Carol","Brian","Amanda","George","Melissa","Edward","Deborah","Ronald","Stephanie","Timothy","Rebecca","Jason","Laura","Jeffrey","Sharon","Ryan","Cynthia","Jacob","Kathleen","Gary","Amy","Nicholas","Shirley","Eric","Angela","Jonathan","Helen","Stephen","Anna","Larry","Brenda","Justin","Pamela","Scott","Nicole","Brandon","Samantha","Benjamin","Katherine","Samuel","Emma","Frank","Ruth","Gregory","Christine","Raymond","Catherine","Alexander","Debra","Patrick","Rachel","Jack","Carolyn","Dennis","Janet","Jerry","Virginia","Tyler","Maria","Aaron","Heather","Jose","Diane","Henry","Julie","Adam","Joyce","Douglas","Victoria","Nathan","Kelly","Peter","Christina","Zachary","Lauren","Kyle","Joan","Walter","Evelyn","Harold","Olivia","Jeremy","Judith","Ethan","Megan","Carl","Cheryl","Keith","Martha","Roger","Andrea","Gerald","Frances","Christian","Hannah","Terry","Jacqueline","Sean","Ann","Arthur","Gloria","Austin","Jean","Noah","Kathryn","Lawrence","Alice","Jesse","Teresa","Joe","Sara","Bryan","Janice","Billy","Doris","Jordan","Madison","Albert","Julia","Dylan","Grace","Bruce","Judy","Willie","Abigail","Gabriel","Marie","Alan","Denise","Juan","Beverly","Logan","Amber","Wayne","Theresa","Ralph","Marilyn","Roy","Danielle","Eugene","Diana","Randy","Brittany","Vincent","Natalie","Russell","Sophia","Louis","Rose","Philip","Isabella","Bobby","Alexis","Johnny","Kayla","Bradley","Charlotte"]
  
lastNames :: [String]
lastNames =
  ["Johnson","Scottish","Williams","Irish","Jones","Miller","Rodriguez","Martinez","Hernandez","Lopez","Gonzales","Wilson","Anderson","Thomas","Taylor","Moore","Jackson","Martin","Lee","Perez","Thompson","White","Harris","Sanchez","Clark","Ramirez","Lewis","Robinson","Jewish","Walker","Young","Allen","King","Wright","Scott","Torres","Nguyen","Hill","Flores","Green","Adams","Nelson","Baker","Hall","Rivera","Campbell","Mitchell","Carter","Roberts","Gomez","Phillips","Evans","Turner","Diaz","Cruz","Edwards","Collins","Reyes","Stewart","Morris","Morales","Murphy","Cook","Rogers","Gutierrez","Ortiz","Cooper","Peterson","Bailey","Reed","Kelly","Howard","Ramos","Cox","Ward","Richardson","Watson","Chavez","Wood","Bennet","Mendoza","Ruiz","Hughes","Price","Alvarez","Castillo","Sanders","Patel","Myers","Long","Ross","Jimenez"]

storeNames :: [String]
storeNames =
  ["Alaska Air Group" ,"Salary.com" ,"Star Merchant Services" ,"Monk Home Improvements" ,"CIGNA" ,"Pearl Architectural Design" ,"A+ Investments" ,"FileMaker Inc., formerly Claris Corp." ,"National Railway Equipment Company" ,"Target Corporation" ,"Frontier Airlines" ,"Ultimate Software" ,"Ecolab" ,"Advansed Teksyztems" ,"Integra Investment Plan" ,"Fresh Start" ,"BlackRock" ,"Infinite Wealth Planners" ,"Creative Wealth Management" ,"Berry Plastics" ,"Amy's Kitchen" ,"Monk House Maker" ,"Bold Ideas" ,"Sun Microsystems, Inc." ,"Federal Home Loan Mortgage Corporation" ,"O'Reilly" ,"CNA" ,"Del Monte Foods" ,"First Rate Choice" ,"Excella" ,"DivX, Inc." ,"Matrix Architectural Service" ,"Home Depot" ,"Oberweis Dairy" ,"The Walt Disney Company" ,"Dun Rite Lawn Maintenance" ,"Ejecta" ,"Capital One" ,"Corning Incorporated" ,"System Star Solutions" ,"Netobill" ,"Local Matters" ,"Afforda Merchant Services" ,"GHD Inc." ,"Emerson Electric Company" ,"Aspyr Media" ,"Marriott Corporation" ,"Fidelity Investments" ,"Zune" ,"Pier 1 Imports" ,"Intuit" ,"Vari-Tec" ,"Adaptec" ,"The Hertz Corporation" ,"Dollar Tree" ,"Lawn N' Order Garden Care" ,"Bucyrus International" ,"Macroserve" ,"Popeyes Chicken & Biscuits" ,"Rockstar Games" ,"Regis Corporation" ,"Mozilla Foundation" ,"i-flex Solutions" ,"Xerox" ,"Universal Studios" ,"Airgas" ,"Arch Coal" ,"State Street Corporation" ,"Royal Gas" ,"Martha Stewart Living Omnimedia" ,"Vermeer Industries" ,"Netstars Matrix Design" ,"Cerner Corporation" ,"Gamma Realty" ,"Practi-Plan" ,"ASARCO (American Smelting And Refining Company)" ,"Adobe Systems Inc." ,"The Lawn Guru" ,"Kimberly-Clark" ,"Lee (jeans)" ,"Creative Wealth" ,"SBC Communications" ,"Home City Ice Co." ,"Monk Home Funding Services" ,"Armstrong World Industries" ,"Dippin' Dots" ,"Modern Architecture Design" ,"International Game Technology (IGT)" ,"Expeditors International" ,"Integra Investment Service" ,"Complete Tech" ,"Abercrombie & Fitch" ,"The Jolly Farmer" ,"Salem Communications" ,"Papa John's Pizza" ,"Micro Design" ,"Medimix International" ,"Boise Cascade" ,"Ace Hardware" ,"Total Yard Management"]

transportNames :: [String]
transportNames =
  ["Shipping Company"]
